-- --------------------------------------------------------
-- #@name
-- Solomon Lisk
-- #@user
-- UA118
-- #@date
-- 02-05-2018
-- #@assign
-- Problem Set 2
-- --------------------------------------------------------
DROP TABLE CUSTOMERS;
DROP TABLE ORDERS;
DROP TABLE ORDER_DETAILS;
DROP TABLE INVENTORY;
DROP TABLE RECIPE;
DROP TABLE BAKERY_ITEMS;
--DROP TABLE TRANSACTION_JOURNAL;
CREATE TABLE CUSTOMERS(
    CUST_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY
            (START WITH 1, INCREMENT BY 1, NO CACHE), 
    CUST_LNAME VARCHAR(30) NOT NULL,
    CUST_FNAME VARCHAR(30) NOT NULL,
    CUST_ADDRESS VARCHAR(100) NOT NULL,    
    CUST_CITY VARCHAR(35) NOT NULL,
    CUST_STATE VARCHAR(20) NOT NULL,
    CUST_ZIP VARCHAR(45) NOT NULL,
    CUST_PHONE VARCHAR(10) NOT NULL, 
    CUST_EMAIL VARCHAR(45) NOT NULL,
    CUST_USERNAME VARCHAR (20) NOT NULL UNIQUE,
    CUST_PASSWORD VARCHAR (45) NOT NULL,
    --CUST_CLASS VARCHAR(12) NOT NULL,
    PRIMARY KEY(CUST_ID)
);
CREATE TABLE INVENTORY(
    INV_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY
            (START WITH 1, INCREMENT BY 1, NO CACHE),
    INV_NAME VARCHAR(30) NOT NULL,
    INV_DESCRIPTION VARCHAR(150) NOT NULL,
    INV_QTY_ONHAND INTEGER NOT NULL,
    INV_REORDER_AMT INTEGER NOT NULL,
    INV_REORDER_PRICE DECIMAL(9,2) NOT NULL,
    PRIMARY KEY(INV_ID)
);
CREATE TABLE BAKERY_ITEMS(
    BAKERY_ITEM_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY
            (START WITH 1, INCREMENT BY 1, NO CACHE), 
    BAKERY_ITEM_NAME VARCHAR(30), 
    BAKERY_ITEM_DESCRIPTION VARCHAR(150),
    BAKERY_ITEM_PRICE DECIMAL(9,2),
    PRIMARY KEY(BAKERY_ITEM_ID)
);

CREATE TABLE ORDERS(
    ORDER_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY
            (START WITH 1, INCREMENT BY 1, NO CACHE),
    ORDER_DATE DATE NOT NULL WITH DEFAULT,
    ORDER_TIME TIME NOT NULL WITH DEFAULT,
    CUSTOMERS_CUST_ID INT NOT NULL,
    PRIMARY KEY(ORDER_ID),
    FOREIGN KEY(CUSTOMERS_CUST_ID) REFERENCES CUSTOMERS(CUST_ID));

CREATE TABLE ORDER_DETAILS(
    ORDER_DETAILS_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY
            (START WITH 1, INCREMENT BY 1, NO CACHE),
    ORDER_ID INTEGER NOT NULL,
	BAKERY_ITEM_ID INTEGER NOT NULL,
	QUANTITY INTEGER NOT NULL,
    PRIMARY KEY(ORDER_DETAILS_ID),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BAKERY_ITEM_ID) REFERENCES BAKERY_ITEMS(BAKERY_ITEM_ID));


CREATE TABLE RECIPE(
    RECIPE_ID INTEGER NOT NULL
        GENERATED ALWAYS AS IDENTITY
            (START WITH 1, INCREMENT BY 1, NO CACHE),
    BAKERY_ITEM_ID INT NOT NULL,
    INV_ID INT NOT NULL,
    INV_QTY_NEEDED INT NOT NULL, 
    PRIMARY KEY(RECIPE_ID),
    FOREIGN KEY(BAKERY_ITEM_ID) REFERENCES BAKERY_ITEMS(BAKERY_ITEM_ID),
    FOREIGN KEY(INV_ID) REFERENCES INVENTORY(INV_ID));

INSERT INTO RECIPE(RECIPE_ID,BAKERY_ITEM_ID,INV_ID,INV_QTY_NEEDED)
VALUES (DEFAULT, '1', '2','1');
INSERT INTO RECIPE(RECIPE_ID,BAKERY_ITEM_ID,INV_ID,INV_QTY_NEEDED)
VALUES (DEFAULT, '3', '1','3');
INSERT INTO RECIPE(RECIPE_ID,BAKERY_ITEM_ID,INV_ID,INV_QTY_NEEDED)
VALUES (DEFAULT, '4', '3','1');
--SELECT *
--FROM ORDER 
--WHERE '2' IN (ORDER_ID, ORDER_DATE, ORDER_TIME, CUSTOMER_CUST_ID);
COMMIT;
